services:
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=wordpress_pass
    expose:
      - 3306
      - 33060
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    restart: always
    build:
      context: .
      dockerfile: alpine.Dockerfile
      args:
        - BEDROCK_DIR=${BEDROCK_DIR}
        - HTTPD_LOGLEVEL=${HTTPD_LOGLEVEL}
        - PHP_FPM_LOGLEVEL=${PHP_FPM_LOGLEVEL}
        - RUNTIME_GROUP=${RUNTIME_GROUP}
        - RUNTIME_USER=${RUNTIME_USER}
        - TLS_HOST=${TLS_HOST}
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./config:/app/config
      - ./web/app/mu-plugins:/app/web/app/mu-plugins
      - ./web/app/plugins:/app/web/app/plugins
      - ./web/app/themes:/app/web/app/themes
      - ./web/app/uploads:/app/web/app/uploads
      - ./.env:/app/.env

volumes:
  db_data: {} # Changed from wordpress-mysql to match the volume used by mysql service
