name: Sync to Gist
on:
  push:
    branches:
      - 'master'

jobs:
  Project-1-Gist:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Gist Repo Sync
          uses: pentatonicfunk/action-gist-repo-sync@v1.8
          with:
            gist_token: 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
            gist_id: 43e451533d917c2e62c2b00879b81f1e
            # source_path: php-hell
